### ISSUE TITLE
Failing to build in Amazon Linux 2023

### ISSUE THREAD

**Issue by meyerovb** [pgspider/jdbc_fdw#30]
Receiving this error

Makefile:51: /contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target '/contrib/contrib-global.mk'.  Stop.

**Comment by chrisfw** [comment]
@meyerovb , the same thing is happening to me.  Were you able to resolve this problem?

**Comment by chrisfw** [comment]
Awesome, thank you @meyerovb !

I saw what looked to be the answer here:  https://github.com/pgspider/jdbc_fdw/issues/11, but you have just given me exactly what I need!

Regards,
Chris

**Comment by meyerovb** [comment]
Worked great I was able to query db2. May use it for Athena in the future not sure.

**Comment by chrisfw** [comment]
Great, thank you for the helpful info!

**Comment by MinhLA1410** [comment]
@meyerovb
Thank you for contributing.
If the issue were resolved. Could you close it?

**Comment by meyerovb** [comment]
@MinhLA1410 This issue wasn’t resolved, I literally paid someone to provide me a workaround for the issue. Did you even try to reproduce this?

**Comment by meyerovb** [comment]
well if you do adjust anything in the documentation, it would be great if u spin up a aws linux 2023 ec2 and test the documented install script on it to make sure there arent any other issues before closing this out.  like the fact it uses "docker compose" vs "docker-compose"

**Comment by MinhLA1410** [comment]
@meyerovb , @mbanck-ntap, 
We apologize for any frustration you may have experienced. The error occurred because the jdbc_fdw extension was built without the PostgreSQL source code or the USE_PGXS flag.

- If you don' use USE_PGXS flag, please place jdbc_fdw extension in folder contrib of PostgreSQL source code then build.
- If you don't use PostgreSQL source code, your machine needs to install postgres on the system and use the USE_PGXS flag to build jdbc_fdw extension

We appreciate you bringing this to our attention and are grateful for the solution you shared. Please assured that we will update the README with detailed instructions for both build methods in the next release to prevent such issues in the future.
Thank you for your understanding and for helping us improve.

**Comment by meyerovb** [comment]
Oh yeah lol sorry confused this with the fact that airbyte open source won’t build on Amazon Linux either, which is why I mentioned docker-compose vs docker-compose :)

**Comment by MinhLA1410** [comment]
@meyerovb ,
Yes. Thank you for understanding.
Could you please close this issue?
